GET https://localhost:7225/api/users/self

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IlU2NjBlOGRjZTgzNjlhNDI3NDA1MzZmYzIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiI2NjBmZWQ1N2Y0NTdkMTZjNDdjN2UzZTUiLCJleHAiOjE3MTIzMjM0MzF9.wqPKL3PY4W_Rwf96QYH0pwTvEp5MQwR2f7tYJHjpZA8
Content-Type: application/json
Accept: application/json